### ISSUE TITLE
Repeated "Prefer" header overrides the previous one in SwaggerUI

### ISSUE THREAD

**Issue by laurenceisla** [PostgREST/postgrest-openapi#26]
I had the idea to repeat the `Prefer` header for each preference that PostgREST has (count, tx, etc.). This would be useful to allow more than one Prefer Header at a time (which is not possible right now in the core repo).

But in SwaggerUI, the other Prefer headers are overridden and have the same value as the first one (since they all have the same `name: Prefer`). A solution would be to just add the valid transactions in the description e.g. "Valid values are: `tx=commit`, `return=minimal`, `...`" or find if it's possible to allow many `enum`s (couldn't find a way yet).

This is the relevant function:
https://github.com/PostgREST/postgrest-openapi/blob/81f5b64ac967e9ba9d4dace6e8fc0a56993b5d1d/sql/postgrest.sql#L615

**Comment by steve-chavez** [comment]
Can `anyOf` work for this? https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/

Also relevant: https://github.com/OAI/OpenAPI-Specification/issues/2109

**Comment by laurenceisla** [comment]
@steve-chavez 

After doing some experiments, using an array type with `anyOf` different values seems to be a valid approach.  But I kinda like the second example more: it uses a JSON object to insert values and serializes it to `key=value` pairs in the CURL execution. E.g.

```json
{
  "count": "exact",
  "return": "representation"
}
```
```bash
curl ... \
  -H `Prefer: count=exact, return=representation`
```

The advantage over `anyOf` is that it validates the type of the value, e.g. it does not allow `count=123` or `max-affected=string`. What  bothers me is that the Swagger Editor does not reference the Schema, which would be useful to get all the possible values, and it does not validate the `enum` values for each property (this is also a problem for `anyOf`). Maybe it's a current limitation of the Swagger Editor and enums, because I also tested Regex using the `pattern` property and it validates it properly (it could be used as an alternative).

**Comment by laurenceisla** [comment]
> What bothers me is that the Swagger Editor does not reference the Schema, which would be useful to get all the possible values, and it does not validate the enum values for each property (this is also a problem for anyOf)

It seems that it behaves differently for each UI. [Redocly](https://redocly.github.io/redoc/) listed the available values and examples nicely, although couldn't test the CURL generation since it doesn't have that feature. In [Rapidoc](https://rapidocweb.com/examples/example1.html#), it also lists the schema but does not generate de CURL example correctly (ignores the header).

I'll fix and implement it that way to avoid blockers. User feedback may be needed here.
