### ISSUE TITLE
Can I Restrict Generated Methods?

### ISSUE THREAD

**Issue by eceppda** [PostgREST/postgrest-openapi#34]
I have created a view and granted a role SELECT privileges access the view. OpenAPI has generated docs including GET, POST, DELETE, and PUT methods for this endpoint. Only GET works (executing from swagger), the others are denied due to lack of permissions.

Is this the expected behavior? The docs seemed to suggest that only methods that are permitted will be generated. I'm wondering if this is working as expected, or if I haven't quite configured permissions correctly.

I'm using v11.2.

**Comment by laurenceisla** [comment]
Hi! This project is not for the current OpenAPI implementation that PostgREST uses, that is still working in the core repository: https://gitub.com/PostgREST/postgrest. Regarding to your issue, it has been reported here: https://github.com/PostgREST/postgrest/issues/1870, so I'm closing this in favor of that issue.
